Repository citec-spbu/agro-fields-service, pull requests merged in 2024-11, with the labels that each got.

#77 61 add 400 and 500 reponses to open api
  src/main/resources/openapi/openapi.yaml
Labels: Documentation, Backend

#82 61 refactor schema and api
  src/main/java/agroscience/fields/v2/controllers/CropRotationsControllerV2.java
  src/main/java/agroscience/fields/v2/controllers/FieldsController.java
  src/main/java/agroscience/fields/v2/controllers/SeasonsController.java
  src/main/java/agroscience/fields/v2/controllers/SoilCompositionsController.java
  src/main/java/agroscience/fields/v2/entities/AbstractEntity.java
  src/main/java/agroscience/fields/v2/entities/ArchivedEntity.java
  src/main/java/agroscience/fields/v2/entities/Contour.java
  src/main/java/agroscience/fields/v2/entities/CropRotationV2.java
  src/main/java/agroscience/fields/v2/entities/FieldV2.java
  src/main/java/agroscience/fields/v2/entities/Season.java
  src/main/java/agroscience/fields/v2/entities/SoilComposition.java
  src/main/java/agroscience/fields/v2/repositories/AbstractRepository.java
  src/main/java/agroscience/fields/v2/repositories/ContoursRepository.java
  src/main/java/agroscience/fields/v2/repositories/CropRotationRepositoryV2.java
  src/main/java/agroscience/fields/v2/repositories/FieldsRepository.java
  src/main/java/agroscience/fields/v2/repositories/SeasonsRepository.java
  src/main/java/agroscience/fields/v2/repositories/SoilCompositionsRepository.java
  src/main/java/agroscience/fields/v2/services/ContoursService.java
  src/main/java/agroscience/fields/v2/services/CropRotationServiceV2.java
  src/main/java/agroscience/fields/v2/services/DefaultService.java
  src/main/java/agroscience/fields/v2/services/FieldsService.java
  src/main/java/agroscience/fields/v2/services/SeasonsService.java
  src/main/java/agroscience/fields/v2/services/SoilCompositionsService.java
  src/main/resources/db/changelog/migrations/2024-10-27_03-create-tables-v2.sql
  src/main/resources/openapi/openapi.yaml
  src/test/java/agroscience/fields/SampleObjectGenerator.java
Labels: Documentation, Backend, Feature

#83 61 Replace soil composition id with id
  src/main/resources/db/changelog/migrations/2024-10-27_03-create-tables-v2.sql
Labels: Bug

#87 73 fix notes
  src/test/java/agroscience/fields/HttpSteps.java
  src/test/java/agroscience/fields/SoilCompositionTest.java
Labels: Bug

#91 61 Fix crop rotation schemas
  src/main/java/agroscience/fields/v2/controllers/CropRotationsControllerV2.java
  src/main/resources/openapi/openapi.yaml
Labels: Bug, Documentation, Backend, Critical
